name: $(BuildDefinitionName)_tag-$(BuildID)_at-$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
    - release/*
    - feature/*

parameters:
- name: tran 
  type: boolean
  displayName: 'Transformation Deployment'
  default: true
- name: dev
  type: boolean
  displayName: 'Dev Deployment'
  default: false
- name: test
  type: boolean
  displayName: 'Test Deployment'
  default: false
- name: int
  type: boolean
  displayName: 'INT Deployment'
  default: false
- name: pp
  type: boolean
  displayName: 'Pre-Prod Deployment'
  default: false
- name: pr
  type: boolean
  displayName: 'Prod Deployment'
  default: false

variables:
- group: dsi-global
- name: tran
  ${{ if eq(parameters.tran, 'true') }}: 
    value: true
  ${{ else }}:
    value: false
- name: dev
  ${{ if eq(parameters.dev, 'true') }}:
    value: true
  ${{ else }}:
    value: false
- name: test
  ${{ if or(eq(parameters.test, 'true'), contains(variables['Build.SourceBranch'],'develop')) }}:
    value: true
  ${{ else }}:
    value: false
- name: int
  ${{ if or(eq(parameters.int, 'true'), contains(variables['Build.SourceBranch'],'release')) }}:
    value: true
  ${{ else }}:
    value: false
- name: pp
  ${{ if or(eq(parameters.pp, 'true'), contains(variables['Build.SourceBranch'],'release')) }}:
    value: true
  ${{ else }}:
    value: false
- name: pr
  ${{ if or(eq(parameters.pr, 'true'), contains(variables['Build.SourceBranch'],'release')) }}:
    value: true
  ${{ else }}:
    value: false

stages:
- ${{ each var in variables }}:
  - ${{ if in(var.key, 'tran','dev','test','int','pp','pr') }}:
    - ${{ if eq(var.value, 'true') }}:
      - stage: Deployment_${{var.Key}}
        variables:
        - group: dsi-${{var.key}}-kv
        - name: SubShortName
          value: $(platformGlobalIdentifier)$(environmentId)
        - name: storageAccountName
          value: $(SubShortName)signinshdstr
        - name: ShdResourceGroupName
          value: $(SubShortName)-shd
        - name: azureCdnName
          value: $(SubShortName)-signin-shd-cdn
        - name: cdnEndpointName
          value: $(subShortName)-signin-shd-cdnep
        displayName: "Deployment [${{var.Key}}]"
        jobs:
        - job: upConCnd
          pool:
            vmImage: 'windows-latest'
          displayName: Updated content of CDN
          steps:
            - powershell: |
                $updatedStorageAccountName = "$(storageAccountName)" -replace '-', ''
                "##vso[task.setvariable variable=storageAccountName;]$updatedStorageAccountName"
              displayName: 'Fix Storage Account Name'
              condition: and(succeeded(), contains(variables['storageAccountName'], '-'))

            - task: AzureCLI@2
              displayName: 'Empty Storage Container Contents'
              inputs:
                ${{ if or(eq(var.key, 'dev'), eq(var.key, 'tran')) }}:
                  azureSubscription: $(devServiceConnection)
                ${{ elseif eq(var.key, 'pr') }}:
                  azureSubscription: $(prodServiceConnection)
                ${{ else }}:
                  azureSubscription: $(testServiceConnection)
                scriptType: pscore
                scriptLocation: inlineScript
                inlineScript: |
                  $publicIp = Invoke-RestMethod -uri https://api.ipify.org

                  az storage account network-rule add -g $(ShdResourceGroupName) --account-name $(storageAccountName) --ip-address $publicIp

                  Start-Sleep 180

                  az storage blob delete-batch --account-name $(storageAccountName) --source $(UIContainerName)

                  Write-Host "##vso[task.setvariable variable=agentIp]$publicIp"


            - task: AzureFileCopy@2
              displayName: Copy Content to Storage Account Container
              inputs:
                SourcePath: $(System.DefaultWorkingDirectory)/dist
                ${{ if or(eq(var.key, 'dev'), eq(var.key, 'tran')) }}:
                  azureSubscription: $(devServiceConnection)
                ${{ elseif eq(var.key, 'pr') }}:
                  azureSubscription: $(prodServiceConnection)
                ${{ else }}:
                  azureSubscription: $(testServiceConnection)
                Destination: AzureBlob
                storage: '$(storageAccountName)'
                ContainerName: '$(UIContainerName)'

            # - task: AzurePowerShell@5
            #   displayName: 'Set Container Public Access Level to Blob (Public)'
            #   inputs:
            #     ${{ if or(eq(var.key, 'dev'), eq(var.key, 'tran')) }}:
            #       azureSubscription: $(devServiceConnection)
            #     ${{ elseif eq(var.key, 'pr') }}:
            #       azureSubscription: $(prodServiceConnection)
            #     ${{ else }}:
            #       azureSubscription: $(testServiceConnection)
            #     ScriptType: 'InlineScript'
            #     Inline: >
            #       Get-AzureRmStorageAccount -ResourceGroupName $(ShdResourceGroupName)
            #       -Name $(storageAccountName) | Set-AzStorageContainerAcl 
            #       -Name $(UIContainerName) -Permission Blob
            #     azurePowerShellVersion: LatestVersion

            - task: AzurePowerShell@5
              displayName: 'Purge CDN Content'
              inputs:
                ${{ if or(eq(var.key, 'dev'), eq(var.key, 'tran')) }}:
                  azureSubscription: $(devServiceConnection)
                ${{ elseif eq(var.key, 'pr') }}:
                  azureSubscription: $(prodServiceConnection)
                ${{ else }}:
                  azureSubscription: $(testServiceConnection)
                azurePowerShellVersion: LatestVersion
                ScriptType: 'InlineScript'
                Inline: >
                  Get -AzureRmCdnEndpoint -ResourceGroupName $(ShdResourceGroupName)
                  -ProfileName $(azureCdnName) -EndpointName $(cdnEndpointName) | Unpublish-AzureRmCdnEndpointContent -PurgeContent '/*'

            - task: AzureCLI@2
              displayName: Remove IP Address From Storage Account
              inputs:
                ${{ if or(eq(var.key, 'dev'), eq(var.key, 'tran')) }}:
                  azureSubscription: $(devServiceConnection)
                ${{ elseif eq(var.key, 'pr') }}:
                  azureSubscription: $(prodServiceConnection)
                ${{ else }}:
                  azureSubscription: $(testServiceConnection)
                scriptType: pscore
                scriptLocation: inlineScript
                inlineScript: 'az storage account network-rule remove -g $(ShdResourceGroupName) --account-name $(storageAccountName) --ip-address $(agentIp)'


              
        #      - task: cboroson.cboroson-ReadSecrets.cboroson-ReadSecrets.cboroson-ReadSecrets@1
        #        displayName: 'Read Secrets: '
        #        inputs:
        #          ConnectedServiceName: $(serviceConnection)
        #          resourceGroupName: $(ShdResourceGroupName)
        #          KeyVaultName: $(keyVaultName)
        #          secretOption: single
        #          secretName: $(secretName)

            - task: PowerShell@2
              displayName: Inline Powershell
              inputs:
                targetType: 'inline'
                script: |
                  $cdnAssetsVersion = [decimal]$(cdnAssetsVersion)
                  $newCdnAssetsVersion = $cdnAssetsVersion+0.1
                  Write-Host "vso[task.setvariable variable=cdnAssetsVersion;]$newCdnAssetsVersion"

        #      - task: cboroson.cboroson.WriteSecrets.cboroson-WriteSecrets.cboroson-WriteSecrets@1
        #        displayName: 'WriteSecrets: cdnAssetsVersion'
        #        inputs:
        #          ConnectedServiceName: $(serviceConnection)
        #          resourceGroupName: $(resourceGroupName)
        #          KeyVaultName: $(keyVaultName)
        #          SecretName: cdnAssetsVersion
        #          SecretValue: $(newCdnAssetsVersion)

